### ISSUE TITLE
"logstash::agent" recipe fails on 1st chef run when using runit

### ISSUE THREAD

**Issue by sonnysideup** [lusis/chef-logstash#142]
**Platform:** Debian 7.1
**Logstash Cookbook:** 0.5.9
**Chef Client:**  11.4.4

Whenever I add the `logstash::agent` recipe to a new node, the Chef run fails with the following error (segment of output):

```
     - enable service runit_service[logstash_agent]

 ================================================================================
 Error executing action `enable` on resource 'runit_service[logstash_agent]'
 ================================================================================


 Mixlib::ShellOut::ShellCommandFailed
 ------------------------------------
 Expected process to exit with [0], but received '1'
 ---- Begin output of /usr/bin/sv restart /etc/service/logstash_agent ----
 STDOUT: timeout: down: /etc/service/logstash_agent: 0s, normally up, want up

 STDERR: 
 ---- End output of /usr/bin/sv restart /etc/service/logstash_agent ----
 Ran /usr/bin/sv restart /etc/service/logstash_agent returned 1



 Cookbook Trace:
 ---------------
 /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:179:in `restart_service'
 /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:95:in `action_enable'


 Resource Declaration:
 ---------------------
 # In /var/chef/cache/cookbooks/logstash/recipes/agent.rb

 110:     runit_service "logstash_agent"
 111:   end
```

I was able to find out that the command failed because, while the tree structure for the library has been laid out, the actual logstash jarfile is missing.

```
opsdude@XXXX:~$ sudo /etc/service/logstash_agent/run
Unable to access jarfile /opt/logstash/agent/lib/logstash.jar

opsdude@XXXX:~$ tree /opt/logstash/agent/
/opt/logstash/agent/
├── bin
├── etc
│   ├── conf.d
│   └── patterns
├── lib
├── log
└── tmp

7 directories, 0 files
```

The `remote_file` and `template` resource responsible for installing the agent jarfile and config, respectively, are defined after the runit service declaration.

Does it not make sense to have these resources defined beforehand?

**Comment by tonyghita** [comment]
@drywheat Do you remember the resolution to your issue? I'm seeing this now :\

**Comment by drywheat** [comment]
The issue is outlined above in full. To summarize, a `runit_service` resource was trying to start the Logstash process before the actual Logstash JAR had been installed.

**Comment by tonyghita** [comment]
Thanks @drywheat
