### ISSUE TITLE
Question - How do you set a LWRP

### ISSUE THREAD

**Issue by spuder** [lusis/chef-logstash#400]
I have a wrapper cookbook that defines my config files. 

I am trying to define a LWRP inside my recipie/default.rb like so:

```
include_recipe 'apt'
include_recipe 'java'
include_recipe 'logstash::server'
logstash_config 'output_elasticsearch' do
  templates_cookbook 'foobar-Logstash-Indexer'
  templates ( output_elasticsearch: => 'config/output_elasticsearch.conf.erb' )
  action [:create]
  notifies :restart, "logstash_service[#{name}]"
end

logstash_config 'input_kafka' do
  templates_cookbook 'foobar-Logstash-Indexer'
  templates ( input_kafka: 'config/input_kafka.conf.erb' )
  action [:create]
  notifies :restart, "logstash_service[#{name}]"
end
```

I get a warning that 'templates' is not a hash. What is the hash supposed to look like? 

Looking at [this issue](https://github.com/lusis/chef-logstash/issues/258), I assume it should look like this

    templates ( output_elasticsearch: 'config/output_elasticsearch.conf.erb')

or this

    templates ( :foo => 'bar' )

or this

    templates { foo: 'bar' }

However none of them work. 

**Update**

I've also tried this sytax as suggested in the irc chanel

```
logstash_config 'output_elasticsearch' do
  templates_cookbook 'foobar-Logstash-Indexer'
  templates ( output_elasticsearch: => 'config/output_elasticsearch.conf.erb' )
  action [:create]
  # notifies :restart, "logstash_service[#{name}]"
end
```

But it throws this error

```
     ================================================================================
       Recipe Compile Error in /tmp/kitchen/cookbooks/foobar-Logstash-Indexer/recipes/default.rb
       ================================================================================

       SyntaxError
       -----------
       /tmp/kitchen/cookbooks/foobar-Logstash-Indexer/recipes/default.rb:16: syntax error, unexpected tLABEL
       ...mplates ( output_elasticsearch: => 'config/output_elasticsea...
       ...                               ^
       /tmp/kitchen/cookbooks/foobar-Logstash-Indexer/recipes/default.rb:16: syntax error, unexpected ')', expecting keyword_end
       /tmp/kitchen/cookbooks/foobar-Logstash-Indexer/recipes/default.rb:23: syntax error, unexpected tLABEL
         templates ( input_kafka: => 'config/input_kafka.conf.erb' )
                          ^
       /tmp/kitchen/cookbooks/foobar-Logstash-Indexer/recipes/default.rb:23: syntax error, unexpected ')', expecting keyword_end

       Cookbook Trace:
       ---------------
         /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
         /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
         /opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:218:in `load_recipe'
         /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:173:in `load_recipe'
         /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
         /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
         /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
         /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
         /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:96:in `load'
         /opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
         /opt/chef/embedded/apps/chef/lib/chef/client.rb:249:in `setup_run_context'
         /opt/chef/embedded/apps/chef/lib/chef/client.rb:445:in `run'
         /opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
         /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
         /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
         /opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
         /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
         /opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
         /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:275:in `block in interval_run_chef_client'
         /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:264:in `loop'
         /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:264:in `interval_run_chef_client'
         /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:242:in `run_application'
         /opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
         /opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
         /opt/chef/bin/chef-solo:52:in `load'
         /opt/chef/bin/chef-solo:52:in `<main>'


       ----------------------
       /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:

        23:
        24:        # Loads a given ruby file, and runs instance_eval against it in the context of the current
        25:        # object.
        26:        #
        27:        # Raises an IOError if the file cannot be found, or is not readable.
        28:        def from_file(filename)
        29:          if File.exists?(filename) && File.readable?(filename)
        30>>           self.instance_eval(IO.read(filename), filename, 1)
        31:          else
        32:            raise IOError, "Cannot open or read #{filename}!"

        34:        end
        35:
        36:        # Loads a given ruby file, and runs class_eval against it in the context of the current
        37:        # object.
        38:        #
        39:        # Raises an IOError if the file cannot be found, or is not readable.


       Running handlers:
       [2015-03-12T22:30:25+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-03-12T22:30:25+00:00] ERROR: Exception handlers complete
       [2015-03-12T22:30:25+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 0 resources updated in 1.87631449 seconds
       [2015-03-12T22:30:25+00:00] ERROR: /tmp/kitchen/cookbooks/foobar-Logstash-Indexer/recipes/default.rb:16: syntax error, unexpected tLABEL
       ...mplates ( output_elasticsearch: => 'config/output_elasticsea...
       ...                               ^
       /tmp/kitchen/cookbooks/foobar-Logstash-Indexer/recipes/default.rb:16: syntax error, unexpected ')', expecting keyword_end
       /tmp/kitchen/cookbooks/foobar-Logstash-Indexer/recipes/default.rb:23: syntax error, unexpected tLABEL
         templates ( input_kafka: => 'config/input_kafka.conf.erb' )
                          ^
       /tmp/kitchen/cookbooks/foobar-Logstash-Indexer/recipes/default.rb:23: syntax error, unexpected ')', expecting keyword_end
       [2015-03-12T22:30:25+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <server-ubuntu-1204>.
>>>>>> Please see .kitchen/logs/server-ubuntu-1204.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '
sudo -E /opt/chef/bin/chef-solo --config /tmp/kitchen/solo.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json
']
>>>>>> ----------------------
```

**Comment by cheeseplus** [comment]
I answered this in #chef IRC but for posterity -

The templates parameter expects a Hash but because of the DSL you'll either need to follow the example below with parens and braces OR set the hash value as a variable beforehand. Also, in the example it is calling #{name} which is a variable not being set so that is going to blow up the notify if 1) the variable is not set and 2) if the name doesn't match an elasticsearch instance.

include_recipe 'apt::default'
include_recipe 'java::default'
include_recipe 'logstash::server'

logstash_config 'server' do
  templates_cookbook 'logstash-wrapper'
  templates({ 'foobar' => 'config/foobar_output_elasticsearch.conf.erb' })
  action [:create]
  notifies :restart, "logstash_service[server]"
end

**Comment by spuder** [comment]
The word 'server' here is the name of the LWRP instance that is defined in logstash::server
